version: '3.8'

services:
  api:
    build: .
    container_name: discord-bot-einstein
    ports:
      - "0.0.0.0:443:443"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G

networks:
  app-network:
    driver: bridge
