version: '3'

services:
  discord-bot-einstein:
    build:
      context: .
      dockerfile: Dockerfile
    image: discord-bot-einstein:latest
    container_name: discord-bot-einstein
    ports:
      - "8090:8090"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - discord_bot_data:/app/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  discord_bot_data:
    driver: local
